name: wikinet
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - gensim
  - pygraphviz
  - mpmath # for powerlaw
  - cython
  - pip
  - pip:
    - bctpy
    - mwparserfromhell
    - sklearn
    - dionysus
    - pybind11
    - cpalgorithm
    - powerlaw
