name: wikinet
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - gensim
  - pip
  - pip:
    - bctpy
    - mwparserfromhell
    - sklearn
    - dionysus
    - pybind11
    - cpalgorithm
