name: wikinet
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - gensim
  - pygraphviz
  - mpmath # for powerlaw
  - cython
  - sphinx
  - line_profiler
  - jupyter_contrib_nbextensions
  - ipywidgets
  - plotly
  - pip
  - pip:
    - bctpy
    - mwparserfromhell
    - sklearn
    - dionysus
    - pybind11
    - cpalgorithm
    - powerlaw
    - sphinx_rtd_theme
    - cufflinks
